### ISSUE TITLE
Add "baoswap-default-token-list" npm package.json

### ISSUE THREAD

**Issue by cdorst** [baofinance/tokenlists#1]
BaoSwap has dependency on `honeyswap-default-token-list` npm package. With a `package.json` file added, we can update the BaoSwap code to use `"baoswap-default-token-list": "https://github.com/baofinance/tokenlists"` in place of `"honeyswap-default-token-list": "^1.3.1"`
https://github.com/baofinance/baoswap-ui-source/blob/da070829f6d5e40d3eec2a00fa76b1ffd95a585a/package.json#L8

**Comment by cdorst** [comment]
See PR #2 for fix

**Comment by fabiaz84** [comment]
Old issue. Deprecated.
