### ISSUE TITLE
Missing BSC Pandaswap tokens submitted pull request

### ISSUE THREAD

**Issue by MarkSchmidty** [baofinance/tokenlists#14]
See Pull Request https://github.com/baofinance/tokenlists/pull/13

Has no conflicts. Information is correct. This will fix the annoyance of needing to enter the token address every time to do a buy or sell as well as remove these misleading warnings:

![image](https://user-images.githubusercontent.com/5949853/116620886-6ee4ee80-a910-11eb-8c91-0f028a68f5fb.png)

**Comment by fabiaz84** [comment]
Old issue. Deprecated.
